name: withthehomies.yoga
favicon: null
layout_spectrum: 0.9133063887711614
typography_spectrum: 0.8980336368549615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff0e8'
    - '#022f12'
    - '#a69f95'
    - '#686a52'
    - '#aa3f39'
  brandStrength: 0.874839317984879
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
