name: withthehomies.yoga
favicon: null
layout_spectrum: 0.9133063887711614
typography_spectrum: 0.38023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040301'
    - '#f8eee4'
    - '#66563f'
    - '#9e8870'
    - '#b1271d'
  brandStrength: 0.874839317984879
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
